#!/usr/bin/env php
<?php

/*
 * This file is part of the Tomuss application.
 *
 * (c) Julien Brochet <mewt@madalynn.eu>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

if (file_exists($file = __DIR__.'/../../autoload.php')) {
    require_once $file;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}

use Madalynn\Tomuss\Console\Application;

$app = new Application();
$app->run();